### ISSUE TITLE
C4ModelTransformer crashes with different container descriptors delivering the same container name

### ISSUE THREAD

**Issue by nils-christian** [archifacts/archifacts#65] opened 2021-09-22 17:16 UTC
Assume I have two _ArtifactContainerDescriptors_, one of _ArtifactContainerType_ A and another one of _ArtifactContainerType_ B. Now assume that I have two classes C and D. C is described by A with the name X, D is described by B, also with name X.

```
.addContainerDescriptor( new ArtifactContainerDescriptor( ) {
	
	@Override
	public ArtifactContainerType type( ) {
		return ArtifactContainerType.of( "A" );
	}
	
	@Override
	public Optional<String> containerNameOf( JavaClass javaClass ) {
		if (javaClass.isEquivalentTo( C.class )) {
			return Optional.of( "X" );
		} else {
			return Optional.empty( );
		}
	}
} )
.addContainerDescriptor( new ArtifactContainerDescriptor( ) {
	
	@Override
	public ArtifactContainerType type( ) {
		return ArtifactContainerType.of( "B" );
	}
	
	@Override
	public Optional<String> containerNameOf( JavaClass javaClass ) {
		if (javaClass.isEquivalentTo( D.class )) {
			return Optional.of( "X" );
		} else {
			return Optional.empty( );
		}
	}
} )
```

While trying to transform the resulting _Application_, the _C4ModelTransformer_ will crash:

> Exception in thread "main" java.lang.IllegalArgumentException: A container named 'X' already exists for this software system.
	at com.structurizr.model.Model.addContainer(Model.java:213)
	at com.structurizr.model.SoftwareSystem.addContainer(SoftwareSystem.java:113)
	at org.archifacts.integration.c4.model.C4ModelTransformer.lambda$transformContainers$1(C4ModelTransformer.java:79)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)

**Comment by OLibutzki** [comment] 2021-09-23 04:41
The question is how to solve this issue... it's a limitation of the C4 model no to allow two containers with the same name...

**Comment by simonbrowndotje** [comment] 2021-09-23 11:09
> The question is how to solve this issue... it's a limitation of the C4 model no to allow two containers with the same name...

It's not a limitation of the C4 model, it's a limitation of the Structurizr for Java library, which doesn't permit duplicate names within a given context ... you can't have two containers named `X` within a single software system. You'll need to rename one of them.

**Comment by OLibutzki** [comment] 2021-09-23 12:45
> Structurizr does enforce this though, and needs unique names for a range of reasons.

Ok, sounds that it's not worth to file a structurizr issue as the behaviour is intended, right?

**Comment by simonbrowndotje** [comment] 2021-09-23 12:46
That's correct, yes, the behaviour is as intended.

**Comment by OLibutzki** [comment] 2021-09-27 18:28
Doing nothing would mean that you cannot use the C4 model  if you run into this situation or you have to adjust the archifacts model.

The latter is not an option in my opinion as the archifacts model is the leading one...

We could think about some kind of C4NamingStrategy which defaults to a SimpleNameStrategy. When you run into conflicts you can configure anyoher strategy.

The strategy might be implemented by providing a FunctionalInterface (ArtifactContainer -> String).

**Comment by OLibutzki** [comment] 2022-01-21 22:58
I overhauled the c4 model transformation fundamentally...

It's possible to finetune the transformation by registering a [ComputationFunction](https://github.com/archifacts/archifacts/blob/main/integration/c4-model/src/main/java/org/archifacts/integration/c4/model/ComputationFunction.java).

I close this issue.

**Closed by OLibutzki** 2022-01-21 22:58 UTC
Labels: bug, clarification-needed
